[package]
name = "renovate"
version = "0.1.0"
edition = "2021"

[lib]
name = "renovate"
path = "src/lib.rs"

[[bin]]
name = "renovate"
path = "src/main.rs"

[features]
default = ["cli"]
cli = ["clap"]


[dependencies]
anyhow = "1.0.65"
async-process = "1.5.0"
async-trait = "0.1.57"
clap = { version = "4.0.7", features = ["derive"], optional = true }
debug-ignore = "1.0.3"
git2 = { version = "0.15.0", default-features = false }
glob = "0.3.0"
itertools = "0.10.5"
pg_query = "0.7.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
sqlformat = "0.2.0"
tokio = { version = "1.21.2", features = ["fs", "rt", "macros", "rt-multi-thread", "tracing"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"

[dev-dependencies]
